- name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: strapi
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: nithin-strapi-v6-service
          cluster: nithin-strapi-v6-cluster
          codedeploy-appspec: appspec.yml 
          codedeploy-application: nithin-strapi-v6-app
          codedeploy-deployment-group: nithin-strapi-v6-dg
          wait-for-service-stability: false # Deenivalla AccessDenied error raadu